apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flux
  description: Flux
  tags:
    - flux
    - third-party
    - opensource
  links:
    - url: https://gitlab.eng.vmware.com/tap-integrations/jenkins-adapter
      title: Source
      icon: user
    - url: https://gitlab.eng.vmware.com/tap-integrations/jenkins-adapter
      title: Contribution Guide
      icon: help
    - url: https://jira.eng.vmware.com/projects/TAPI
      title: Backlog
      icon: help
spec:
  type: library
  lifecycle: production
  owner: group:integrations
  system: tap
