apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/managed-by-location: url:http://github.com/backstage/backstage/blob/master/catalog-info.yaml 
    backstage.io/source-location: url:https://github.com/my-org/my-service/
  name: jenkins-adaptor
  description: Jenkins Adaptor
  tags:
    - golang
    - tekton
    - cli
    - jenkins
  links:
    - url: https://gitlab.eng.vmware.com/tap-integrations/jenkins-adapter
      title: Source
      icon: user
    - url: https://gitlab.eng.vmware.com/tap-integrations/jenkins-adapter
      title: Contribution Guide
      icon: help
    - url: https://jira.eng.vmware.com/projects/TAPI
      title: Backlog
      icon: help
    - url: https://runway-ci.eng.vmware.com/teams/tap-integrations/pipelines/jenkins-adapter
      title: CI
      icon: help  
spec:
  type: service
  lifecycle: production
  owner: group:integrations
  system: tap
  dependsOn: ['component:tekton']
